### ISSUE TITLE
optimize all

### ISSUE THREAD

**Issue by shrddr** [Thell/bdo-housecraft#1]
it's generating **all**_lodging_storage.json but there's no command to optimize all regions, only specific one (i'd imagine just `housecraft.exe --optimize`, but doesn't work, requires `-R Velia` argument)

**Comment by Thell** [comment]
It's not the most intuitive I guess but for _all_ regions... `-R ALL`

`housecraft --optimize -R ALL --limit-warehouse 184`

Help should be more helpful in this case.

-R, --region <REGION>    specific region or ALL

**Comment by Thell** [comment]
Added to help.
